# =============================================================================
# run_policies.tf — run policies: rules a workflow run must satisfy, or the run
# is blocked (or only reported, in dry-run mode).
# =============================================================================
# What this file manages
#   StepSecurity evaluates run policies when a workflow run starts. One policy
#   bundles up to five sub-policies, each switched on by an enable_* flag:
#     action policy          which actions may be used and whether they must be SHA-pinned
#     runs-on policy         which runner labels are disallowed (or exclusively allowed)
#     harden-runner policy   every targeted job must run step-security/harden-runner
#     secrets policy         block runs that try to exfiltrate secrets
#     compromised actions    block actions StepSecurity threat intel flags as compromised
#
#   var.run_policies -> stepsecurity_github_run_policy   one instance per map entry
#
# Where the values come from
#   Entries live in terraform.tfvars (or examples/*.tfvars). The entry's
#   `policy` object IS the provider's policy_config block, mirrored attribute
#   by attribute in inputs.tf, so examples from the provider docs paste in
#   unchanged. This file only adds the two identifiers the provider requires
#   inside policy_config (owner, name) so tfvars never repeats them.
#
# How to run (from stepsecurity/; credentials come from the environment)
#   export STEP_SECURITY_CUSTOMER=<tenant> STEP_SECURITY_API_KEY=<key>
#   terraform init -backend-config="key=stepsecurity/terraform.tfstate"
#   terraform plan            # uses terraform.tfvars, or -var-file=examples/03-run-policies.tfvars
#
# Adopting a policy that already exists: import ID  <org>/<policy_id>
#   policy_id is generated by StepSecurity — read it from the dashboard URL,
#   from `terraform output -json run_policies`, or from the
#   stepsecurity_github_run_policies data source.
#   import { to = stepsecurity_github_run_policy.this["pin-actions"], id = "acme-platform/9f1c2d3e" }
# =============================================================================

# ===== run_policies -> stepsecurity_github_run_policy ========================
# Minimal tfvars entry (every action allowed, but only when SHA-pinned):
#   run_policies = { "pin-actions" = { owner = "acme-platform", policy = { enable_action_policy = true, require_pinned_actions = true, allowed_actions = { "*/*" = "allow" } } } }
resource "stepsecurity_github_run_policy" "this" { # address: stepsecurity_github_run_policy.this["<map key>"]
  for_each = var.run_policies                      # one instance per entry of the map; each.key = map key, each.value = the entry object typed in inputs.tf

  owner        = each.value.owner                              # (required) GitHub org the policy belongs to; tfvars: owner = "<org>"
  name         = coalesce(each.value.name, each.key)           # (required) dashboard name: the entry's `name` when set, otherwise the map key; tfvars: name = "..." (optional)
  all_repos    = each.value.repositories == null ? true : null # true = whole org when the entry lists no repositories; null (not false) when it does, so the provider computes it and shows no drift
  repositories = each.value.repositories                       # (optional) repo names the policy is scoped to; null (default) = every repo in the org; tfvars: repositories = ["payments-api"]

  # The provider's policy_config block. merge() takes the entry's `policy`
  # object as-is and overlays the two identifiers the provider requires inside
  # the block (policy_config.owner / policy_config.name), so they always match
  # the resource above and are never typed in tfvars. Optional attributes the
  # entry leaves unset arrive as null, which the provider treats as "not
  # configured". At least ONE enable_* flag must be true or the API rejects
  # the policy at plan time.
  policy_config = merge(each.value.policy, {    # everything set under policy = { ... } in tfvars, plus:
    owner = each.value.owner                    # same org as the resource (required by the provider inside policy_config)
    name  = coalesce(each.value.name, each.key) # same dashboard name as the resource (required by the provider inside policy_config)
  })
  # ---- What tfvars can set under policy = { ... } (all optional, null = off) --
  #   is_dry_run = true                                     # report violations without blocking (default false); start every policy this way
  #   -- action policy --
  #   enable_action_policy = true                           # turn the sub-policy on
  #   allowed_actions = { "*/*" = "allow" }                 # map of action pattern -> "allow": "actions/checkout@v4" (exact) | "actions/checkout" (any ref) | "my-org/*" | "*/*" (all)
  #   require_pinned_actions = true                         # every action must be pinned to a full commit SHA (needs enable_action_policy)
  #   actions_to_exempt_while_pinning = ["my-org/*"]        # actions that may still use a tag/branch; "*/*" is rejected here (put it in allowed_actions instead)
  #   -- runs-on policy --
  #   enable_runs_on_policy = true                          # turn the sub-policy on
  #   runs_on_mode = "disallowed"                           # disallowed (default) = block labels in disallowed_runner_labels | allowed = permit ONLY allowed_runner_labels / allowed_runner_constraints
  #   disallowed_runner_labels = ["self-hosted"]            # labels that block a job in disallowed mode
  #   allowed_runner_labels = ["ubuntu-latest"]             # labels permitted in allowed mode (required for that mode; ignored in disallowed mode)
  #   allowed_runner_constraints = { family = ["m7a"] }     # runs-on.com key=value constraints permitted in allowed mode; lowercase keys, >= 1 value each
  #   enable_standard_runner_labels = true                  # add GitHub-hosted labels (ubuntu-latest, ...) to disallowed_runner_labels AND harden_runner_target_labels
  #   -- harden-runner policy --
  #   enable_harden_runner_policy = true                    # turn the sub-policy on
  #   harden_runner_target_labels = []                      # [] = every job | ["ubuntu-latest"] = only jobs whose runs-on matches | omitted = backend value left untouched
  #   harden_runner_custom_actions = ["my-org/hr-wrapper"]  # extra actions accepted as harden-runner equivalents
  #   require_policy_store = true                           # the harden-runner step must set use-policy-store: true (legacy policy: input does not count)
  #   block_job_container = true                            # block targeted jobs that run entirely in a job-level container: (not monitorable)
  #   -- secrets policy --
  #   enable_secrets_policy = true                          # turn the sub-policy on
  #   exempted_users = ["dependabot[bot]"]                  # users / bots whose runs skip the secrets policy
  #   bulk_secrets_only_mode = true                         # only act on high-risk bulk secret-exposure attempts (default false = every secret reference)
  #   secrets_analyze_default_branch = true                 # also evaluate runs on the default branch (default false = non-default branches only)
  #   -- compromised actions policy --
  #   enable_compromised_actions_policy = true              # block actions flagged as compromised by StepSecurity threat intel
  #   -- block message --
  #   pr_comment_template = "Blocked by policy: ..."        # custom PR comment when a run is blocked (supports placeholders); omitted = StepSecurity default text
}
# ---- Provider attributes NOT exposed by this layout (stepsecurity v0.0.44) ---
#   all_orgs                     tenant-wide policy (every org at once). This layout is
#                                per-org; to expose it add `all_orgs = optional(bool)` to the
#                                run_policies object type in inputs.tf and pass
#                                `all_orgs = each.value.all_orgs` here.
#   all_repos                    derived above from `repositories`, not settable directly.
#   policy_config.owner / .name  merged in from owner / the map key, not settable separately.
#   Computed (read-only): policy_id (needed for the import ID <org>/<policy_id>),
#                         created_at, created_by, last_updated_at, last_updated_by.
#   Every other policy_config attribute of the provider is in the `policy`
#   object type (inputs.tf) and listed above.
# -----------------------------------------------------------------------------
