# =============================================================================
# suppressions.tf — suppression rules: detections you have reviewed and
# accepted, so they stop raising alerts.
# =============================================================================
# What this file manages
#   Harden-Runner (StepSecurity's agent inside a GitHub Actions job) and the
#   PR checks raise a DETECTION for anything unusual. When a human has looked
#   at one and it is expected — the coverage upload to codecov.io, a test
#   fixture that looks like a secret — a suppression rule tells StepSecurity
#   to ignore every future detection that matches it. A rule is
#     type    WHAT kind of detection (10 types, listed on `type` below)
#     scope   WHERE it may happen: owner (org, or "*" = the whole tenant),
#             repo / workflow / job ("*" = any)
#     detail  the fields that identify the detection for that type
#             (process + destination, host + file_path, secret_type, ...)
#   The only action the provider supports today is "ignore", so this file
#   hard-codes it.
#
#   var.suppression_rules -> stepsecurity_github_supression_rule   one instance per map entry, keyed by rule name
#   (the provider spells the resource type "supression", one p — keep it)
#
# Where the values come from
#   Entries live in terraform.tfvars (or examples/*.tfvars); the object type is
#   in inputs.tf. No tenant-wide defaults are involved; repo / workflow / job
#   default to "*" in the object type. The provider checks at plan time that
#   the detail fields the type needs are present.
#
# How to run (from stepsecurity/; credentials come from the environment)
#   export STEP_SECURITY_CUSTOMER=<tenant> STEP_SECURITY_API_KEY=<key>
#   terraform init -backend-config="key=stepsecurity/terraform.tfstate"
#   terraform plan            # uses terraform.tfvars, or -var-file=examples/07-notifications-and-suppressions.tfvars
#
# Adopting a rule that already exists: import ID  <rule_id>
#   rule_id is generated by StepSecurity; the provider copies the import ID
#   straight into its computed rule_id attribute and reads the rule by it.
#   Find it in the dashboard's suppression-rules page, or for managed rules in
#   `terraform output -json suppression_rules` (outputs.tf).
#   import { to = stepsecurity_github_supression_rule.this["platform-codecov-upload"], id = "<rule_id>" }
# =============================================================================

# ===== suppression_rules -> stepsecurity_github_supression_rule ==============
# Minimal tfvars entry (ignore anomalous outbound calls to *.codecov.io from any process, anywhere in the org):
#   suppression_rules = { "platform-codecov-upload" = { owner = "acme-platform", type = "anomalous_outbound_network_call", process = "*", destination = { domain = "*.codecov.io" } } }
resource "stepsecurity_github_supression_rule" "this" { # address: stepsecurity_github_supression_rule.this["<rule name>"]
  for_each = var.suppression_rules                      # one instance per entry of the map; each.key = rule name, each.value = the entry object typed in inputs.tf

  name        = each.key               # (required) rule name shown in the dashboard — the map key itself
  owner       = each.value.owner       # (required) GitHub org the rule applies to, or "*" = every org in the tenant; tfvars: owner = "acme-platform"
  type        = each.value.type        # (required) detection type: anomalous_outbound_network_call | suspicious_network_call | https_outbound_network_call | secret_in_build_log | secret_in_artifact | source_code_overwritten | action_uses_imposter_commit | runner_worker_memory_read | privileged_container | reverse_shell
  action      = "ignore"               # what happens to a matching detection; "ignore" is the only value the provider accepts today, so it is fixed here and not settable in tfvars
  description = each.value.description # (optional) why the detection is accepted, shown in the dashboard; null (default) = none; tfvars: description = "Coverage upload is expected"

  # Scope: where the rule applies; "*" = any. Narrow it as far as you can so
  # the rule cannot hide the same detection somewhere unexpected.
  repo     = each.value.repo     # (optional) repo name; "*" (layout default) = every repo of the org; tfvars: repo = "payments-api"
  workflow = each.value.workflow # (optional) workflow name; "*" (layout default) = every workflow; tfvars: workflow = "ci.yml"
  job      = each.value.job      # (optional) job name; "*" (layout default) = every job; tfvars: job = "test"

  # Detail fields: each `type` needs its own and the provider rejects the rule
  # at plan time when one is missing. The entry sets only the fields its type
  # needs; the others arrive here as null and are not sent.
  process       = each.value.process       # REQUIRED for anomalous_outbound_network_call, runner_worker_memory_read, privileged_container, reverse_shell: process name, exact or wildcard ("curl", "*node", "*.exe", "*"); null otherwise
  secret_type   = each.value.secret_type   # REQUIRED for secret_in_build_log and secret_in_artifact: secret category exactly as the detection names it (e.g. "GitHub Token", "JSON Web Token"); null otherwise
  artifact_name = each.value.artifact_name # REQUIRED for secret_in_artifact (together with secret_type): name of the uploaded artifact; null otherwise
  endpoint      = each.value.endpoint      # REQUIRED for suspicious_network_call: the flagged endpoint as the detection shows it, host:port, wildcards ok; null otherwise
  host          = each.value.host          # REQUIRED for https_outbound_network_call (together with file_path): host of the flagged HTTPS call, wildcards ok; null otherwise
  file          = each.value.file          # REQUIRED for source_code_overwritten: name of the overwritten file; null otherwise
  file_path     = each.value.file_path     # REQUIRED for https_outbound_network_call: path of the program that made the call ("*" = any caller); OPTIONAL for source_code_overwritten: path of the overwritten file, narrowing `file` (null = any path); null otherwise
  github_action = each.value.github_action # REQUIRED for action_uses_imposter_commit: the action as written after `uses:`, e.g. "actions/checkout" (no ref); null otherwise
  destination   = each.value.destination   # REQUIRED for anomalous_outbound_network_call (together with process): { domain = "*.codecov.io" } OR { ip = "192.168.*.1:443" }, never both, wildcards ok; null otherwise
  # ---- What tfvars can set on a suppression_rules entry
  #   owner       = "acme-platform"                   # required; "*" = every org in the tenant
  #   type        = "anomalous_outbound_network_call" # required; one of the 10 types listed on `type` above
  #   description = "Coverage upload is expected"     # optional (default: none)
  #   repo        = "payments-api"                    # optional (default "*" = any repo)
  #   workflow    = "ci.yml"                          # optional (default "*" = any workflow)
  #   job         = "test"                            # optional (default "*" = any job)
  #   -- plus exactly the detail fields the type needs (leave every other one out) --
  #   anomalous_outbound_network_call   process = "*"                  destination = { domain = "*.codecov.io" }   # or destination = { ip = "10.0.*.1:443" }; never both
  #   suspicious_network_call           endpoint = "*.ngrok-free.app:443"
  #   https_outbound_network_call       host = "*.s3.amazonaws.com"    file_path = "/usr/local/bin/aws"            # file_path: the calling program, "*" = any
  #   secret_in_build_log               secret_type = "JSON Web Token"
  #   secret_in_artifact                secret_type = "Private Key"    artifact_name = "test-fixtures"
  #   source_code_overwritten           file = "package-lock.json"     file_path = "web/package-lock.json"         # file_path optional here
  #   action_uses_imposter_commit       github_action = "actions/setup-node"
  #   runner_worker_memory_read         process = "gdb"
  #   privileged_container              process = "docker"
  #   reverse_shell                     process = "tmate"
}
# ---- Provider attributes NOT exposed by this layout (stepsecurity v0.0.44) ---
#   action    fixed to "ignore" above — the only value the provider accepts.
#             When StepSecurity adds another action, expose it with
#             `action = optional(string, "ignore")` in the suppression_rules
#             object type (inputs.tf) and `action = each.value.action` here.
#   Every other argument (name, owner, type, description, repo, workflow, job,
#   process, secret_type, artifact_name, endpoint, host, file, file_path,
#   github_action, destination{domain, ip}) is passed through.
#   Computed (read-only): rule_id — StepSecurity's ID for the rule; it is the
#   import ID and is shown by `terraform output -json suppression_rules`.
# -----------------------------------------------------------------------------
